// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi0w5lzlvtZnstVRIICDivW1QaqA3HPYw',
    appId: '1:313981550890:web:f1790cf045a08f7d3a9e53',
    messagingSenderId: '313981550890',
    projectId: 'tastytable-32cd1',
    authDomain: 'tastytable-32cd1.firebaseapp.com',
    storageBucket: 'tastytable-32cd1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD385Vqrqt2WEXxepeytI44PyiVdRY6_20',
    appId: '1:313981550890:android:d2b04cf868a19c143a9e53',
    messagingSenderId: '313981550890',
    projectId: 'tastytable-32cd1',
    storageBucket: 'tastytable-32cd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYFSHN7j0w_ilG5M8w4t1eFkNwHjD5AC8',
    appId: '1:313981550890:ios:bf2c2381436499953a9e53',
    messagingSenderId: '313981550890',
    projectId: 'tastytable-32cd1',
    storageBucket: 'tastytable-32cd1.firebasestorage.app',
    iosBundleId: 'com.example.tastytable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYFSHN7j0w_ilG5M8w4t1eFkNwHjD5AC8',
    appId: '1:313981550890:ios:bf2c2381436499953a9e53',
    messagingSenderId: '313981550890',
    projectId: 'tastytable-32cd1',
    storageBucket: 'tastytable-32cd1.firebasestorage.app',
    iosBundleId: 'com.example.tastytable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi0w5lzlvtZnstVRIICDivW1QaqA3HPYw',
    appId: '1:313981550890:web:c399e0c9de26a2083a9e53',
    messagingSenderId: '313981550890',
    projectId: 'tastytable-32cd1',
    authDomain: 'tastytable-32cd1.firebaseapp.com',
    storageBucket: 'tastytable-32cd1.firebasestorage.app',
  );

}