// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7eXyHi9eDAy9n8hHAZ-4Ng6q7fyIA70s',
    appId: '1:832452642758:web:ddcef5741fbc0837ce14c7',
    messagingSenderId: '832452642758',
    projectId: 'tastytable-cef88',
    authDomain: 'tastytable-cef88.firebaseapp.com',
    storageBucket: 'tastytable-cef88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT7M28zVH93ALLBH9-CraQ9YY9jYZKVj0',
    appId: '1:832452642758:android:a088411a602b1ba2ce14c7',
    messagingSenderId: '832452642758',
    projectId: 'tastytable-cef88',
    storageBucket: 'tastytable-cef88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3PGX0qiM01xUB7CyOSm8g-Y6hcZILMAg',
    appId: '1:832452642758:ios:b234b130dff4084cce14c7',
    messagingSenderId: '832452642758',
    projectId: 'tastytable-cef88',
    storageBucket: 'tastytable-cef88.firebasestorage.app',
    iosBundleId: 'com.example.tastytable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3PGX0qiM01xUB7CyOSm8g-Y6hcZILMAg',
    appId: '1:832452642758:ios:b234b130dff4084cce14c7',
    messagingSenderId: '832452642758',
    projectId: 'tastytable-cef88',
    storageBucket: 'tastytable-cef88.firebasestorage.app',
    iosBundleId: 'com.example.tastytable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7eXyHi9eDAy9n8hHAZ-4Ng6q7fyIA70s',
    appId: '1:832452642758:web:46d5fe1ec7dbc4c2ce14c7',
    messagingSenderId: '832452642758',
    projectId: 'tastytable-cef88',
    authDomain: 'tastytable-cef88.firebaseapp.com',
    storageBucket: 'tastytable-cef88.firebasestorage.app',
  );
}
